version: "3.1"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: db_frajola
    ports:
      - "5432:5432"
    volumes:
      - C:\Users\walla\frazola_pizzaria\backup:/var/lib/postgresql/data
